name: Integration Tests

on:
  workflow_call:

jobs:
  integration:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '18'
      - name: Install dependencies
        run: npm ci
      - name: Run Make.com scenario tests
        run: npm run test:make
      - name: API Endpoint Tests
        run: npm run test:api
      - name: Cross-platform Compatibility
        run: npm run test:compat
      - name: Upload Test Results
        uses: actions/upload-artifact@v4
        with:
          name: integration-test-results
          path: test-results
